// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  default: [
    {type: 'autogenerated', dirName: '.'},
    {
      type: 'category',
      label: 'Communities',
      items: [
        {
          type: 'link',
          label: 'RomDrop facebook page',
          href: 'https://www.facebook.com/groups/romdrop',
        },
        {
          type: 'link',
          label: 'RomDrop tuning chat',
          href: 'https://www.facebook.com/messages/c/5874843909269827/t/5986216474790292',
        },
        {
          type: 'link',
          label: 'NC Miata forum',
          href: 'https://forum.miata.net/vb/forumdisplay.php?f=151',
        },
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      items: [
        {
          type: 'link',
          label: 'OEM ROMs',
          href: 'https://github.com/VIRUXE/ncmiatatuning-docs/tree/main/static/roms',
        },
        {
          type: 'link',
          label: 'MX5 Owner manual',
          href: '2008-mx-5-owners-manual.pdf',
        },
      ],
    },
    {
      type: 'category',
      label: 'External resources',
      items: [
        {
          type: 'link',
          label: 'RomDrop - GitHub',
          href: 'https://github.com/speepsio/romdrop',
        },
        {
          type: 'link',
          label: 'RomDrop - Rabbit hole thread',
          href: 'https://forum.miata.net/vb/showthread.php?t=630805&page=212',
        },
        {
          type: 'link',
          label: 'Roadster blog - NC Technical',
          href: 'https://www.roadster.blog/p/technical.html',
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
